services:
  bot:
    build: .
    image: comp7940_groupi_bot:latest
    container_name: comp7940_groupi_bot
    env_file:
      - .env    
    environment:
      - TZ=Asia/Hong_Kong
    deploy:
      replicas: 1  
      restart_policy:
        condition: on-failure
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge 