name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push image to ACR
      uses: azure/docker-login@v1
      with:
        login-server: groupiacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build -t groupiacr.azurecr.io/comp7940_groupi_bot:${{ github.sha }} .
        docker push groupiacr.azurecr.io/comp7940_groupi_bot:${{ github.sha }}

    - name: Check and stop existing instances
      run: |
        echo "Checking for existing instances..."
        RUNNING_INSTANCES=$(az container list -g ${{ secrets.RESOURCE_GROUP }} --query "[?name=='comp7940-groupi-bot'].name" -o tsv | wc -l)
        if [ "$RUNNING_INSTANCES" -gt "0" ]; then
          echo "Stopping existing instance..."
          az container stop --name comp7940-groupi-bot --resource-group ${{ secrets.RESOURCE_GROUP }}
          echo "Waiting for instance to stop completely..."
          sleep 30
          echo "Deleting existing instance..."
          az container delete -g ${{ secrets.RESOURCE_GROUP }} -n comp7940-groupi-bot --yes
          echo "Waiting for deletion to complete..."
          sleep 30
        fi

    - name: Deploy to Azure Container Instance
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: comp7940-groupi-bot
        image: groupiacr.azurecr.io/comp7940_groupi_bot:${{ github.sha }}
        name: comp7940-groupi-bot
        location: 'East Asia'
        registry-login-server: groupiacr.azurecr.io
        registry-username: ${{ secrets.ACR_USERNAME }}
        registry-password: ${{ secrets.ACR_PASSWORD }}
        restart-policy: Always
        cpu: 1
        memory: 1.5
        assign-identity: true
        secure-environment-variables: |
          KEY_VAULT_NAME=COMP7940-GroupI-Key
          KEY_VAULT_URL=https://comp7940-groupi-key.vault.azure.net/
          AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
        environment-variables: |
          TZ=Asia/Hong_Kong

    - name: Verify deployment
      run: |
        echo "Waiting for container to start..."
        sleep 30
        INSTANCE_COUNT=$(az container list -g ${{ secrets.RESOURCE_GROUP }} --query "[?name=='comp7940-groupi-bot'].name" -o tsv | wc -l)
        if [ "$INSTANCE_COUNT" -ne "1" ]; then
          echo "Error: Incorrect number of instances running"
          exit 1
        fi
        echo "Deployment verified: One instance running"
        echo "Container logs:"
        az container logs --name comp7940-groupi-bot --resource-group ${{ secrets.RESOURCE_GROUP }}
